// <auto-generated />
using System;
using CRSP.IPS.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRSP.IPS.Infrastructure.Persistencia.Migracoes
{
    [DbContext(typeof(ContextoIps))]
    partial class ContextoIpsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.Bloqueio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AplicadoNoFirewallEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Asn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BloqueadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncerradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpChave")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelReincidencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocorrencias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Organizacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaisCodigo")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisNome")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegraId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Simulado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BloqueadoEm");

                    b.HasIndex("Ip");

                    b.HasIndex("IpChave");

                    b.HasIndex("RegraId");

                    b.HasIndex("Status", "Simulado");

                    b.ToTable("Bloqueios", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.CoincidenciaListaExterna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int>("ListaExternaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PrimeiraEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("UltimaFonte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UltimaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UltimoCodigoStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UltimoSite")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UltimaEm");

                    b.HasIndex("ListaExternaId", "Ip")
                        .IsUnique();

                    b.ToTable("CoincidenciasListasExternas", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AplicacaoPaises")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AtualizadaPor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoHttpErr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoLogIis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("JanelaReincidenciaDias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModoPaises")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ModoSimulacao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MonitorarEventosWindows")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MonitorarHttpErr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MonitorarLogIis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaisesPolitica")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortasPolitica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetencaoEventosDias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemposBloqueio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersaoRegrasPadrao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracao", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.ConfiguracaoGeoIp", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AtualizacaoAutomatica")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AtualizacaoSolicitada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaveProtegida")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContaId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalChave")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaAtualizacaoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaVerificacaoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoResultado")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UltimoResultadoSucesso")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracaoGeoIp", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.EntradaLista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadaPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FimChave")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("InicioChave")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sistema")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Faixa")
                        .IsUnique();

                    b.ToTable("Listas", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.EntradaListaExterna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FimChave")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("InicioChave")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ListaExternaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referencia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListaExternaId", "InicioChave");

                    b.ToTable("EntradasListasExternas", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.EventoSeguranca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodigoStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Fonte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metodo")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisCodigo")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Site")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ip");

                    b.HasIndex("OcorridoEm");

                    b.ToTable("Eventos", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.ListaExterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AtualizacaoSolicitada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Formato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervaloHoras")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteEntradas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Modo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Removidas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimaAtualizacaoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaVerificacaoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Urls")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ListasExternas", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.PosicaoLeitura", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadaEm")
                        .HasColumnType("TEXT");

                    b.Property<long>("Posicao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Chave");

                    b.ToTable("PosicoesLeitura", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Alvo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OcorridoEm");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.RegraDeteccao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Criterio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Fonte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JanelaSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteOcorrencias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Padrao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Regras", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.RegraFirewallDesativada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DesativadaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("RegrasFirewallDesativadas", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.StatusWorker", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnderecosNoFirewall")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventosProcessados")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Maquina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegrasNoFirewall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumoPoliticaPaises")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaSincronizacaoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoErroEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimoSinalEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusWorker", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.Bloqueio", b =>
                {
                    b.HasOne("CRSP.IPS.Domain.Entidades.RegraDeteccao", "Regra")
                        .WithMany()
                        .HasForeignKey("RegraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Regra");
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.CoincidenciaListaExterna", b =>
                {
                    b.HasOne("CRSP.IPS.Domain.Entidades.ListaExterna", null)
                        .WithMany()
                        .HasForeignKey("ListaExternaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CRSP.IPS.Domain.Entidades.EntradaListaExterna", b =>
                {
                    b.HasOne("CRSP.IPS.Domain.Entidades.ListaExterna", null)
                        .WithMany()
                        .HasForeignKey("ListaExternaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
