<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Product>CRSPIPS</Product>
    <Company>crsp.dev</Company>
    <Authors>crsp.dev</Authors>
    <Copyright>Copyright © crsp.dev</Copyright>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
